apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: promo-testing-product
spec:
  promotionFlows:
    - name: qa-prod
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '[GitOps] Update image tag to vPR-*'

