gitops-runtime:
  global:
    codefresh:
      accountId: 67b67abfa8342f30a57b087a
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: gitops-default
