apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: qa-prod
  annotations:
    description: ""
spec:
  triggerEnvironment: qa-test
  steps:
    - environment: prod-test
      dependsOn:
        - qa-test
      policy:
        action: commit
