# DO NOT REMOVE the following attributes:
# annotations.codefresh.io/workflow-origin (identifies type of Workflow Template as Promotion Workflow)
# annotations.version (identifies version of Promotion Workflow used)
# annotations.description (identifies intended use of the Promotion Workflow)
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: promotion-workflow-test
  annotations:
    version: 0.0.1
    codefresh.io/workflow-origin: promotion
    description: Test promotion workflow
spec:
  arguments:
    parameters:
      - name: APP_NAME
      - name: APP_NAMESPACE
      - name: SERVER_URL
        value: argo-cd-server.{{workflow.parameters.APP_NAMESPACE}}.svc.cluster.local
  entrypoint: starter-manual-sync
  templates:
    - name: starter-manual-sync
      dag:
        tasks:
          - name: sync
            templateRef:
              name: argo-hub.argocd.0.0.1
              template: sync
            arguments:
              parameters:
                - name: app
                  value: '{{workflow.parameters.APP_NAME}}'
                - name: flags
                  value: '--prune --timeout 120'
                - name: serverUrl
                  value: '{{workflow.parameters.SERVER_URL}}'
                - name: opts
                  value: '--grpc-web --plaintext'
                - name: tokenSecret
                  value: argocd-token
                - name: tokenSecretKey
                  value: token
          - name: wait
            templateRef:
              name: argo-hub.argocd.0.0.1
              template: wait
            arguments:
              parameters:
                - name: app
                  value: '{{workflow.parameters.APP_NAME}}'
                - name: flags
                  value: '--health --timeout 120'
                - name: serverUrl
                  value: '{{workflow.parameters.SERVER_URL}}'
                - name: opts
                  value: '--grpc-web --plaintext'
                - name: tokenSecret
                  value: argocd-token
                - name: tokenSecretKey
                  value: token
            depends: sync
          - name: send-message
            templateRef:
              name: argo-hub.slack.0.0.2
              template: send-message
            arguments:
              parameters:
                - name: SLACK_HOOK_URL
                  value: <SLACK_HOOK_URL>
                - name: SLACK_TEXT
                  value: Successfully promoted {{workflow.parameters.APP_NAME}}!
            depends: wait
  serviceAccountName: cf-default-promotion-workflows-sa