apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cf-git-sources
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
